apiVersion: v1
kind: Pod
metadata:
  name: app-server
  labels:
    app: myapp
spec:
  containers:
  - name: app-server
    image: bvijaycom/appserver:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32001
  type: NodePort
